/**
 * Monero keys, addresses and seed phrases.
 *
 * This is the highest-consequence code on the site. Everything else fails
 * loudly: a wrong GIF looks wrong. A wrong derivation here produces a perfectly
 * valid-looking address that nobody can ever spend from, and there is no way to
 * find out except by losing the money.
 *
 * So the tests are written against things that were not produced by this code:
 * published Keccak vectors, the published ed25519 base point, and a real
 * address generated by the official Monero wallet. Round-trip tests are here
 * too, but they are the weakest kind of evidence — code can round-trip its own
 * mistakes perfectly — so they are never the only check on anything.
 *
 * The one property with no external vector available is private-to-public, and
 * the page says so and tells people to confirm against the official wallet
 * before funding anything. A test file should not pretend to prove more than
 * it does.
 */

import { describe, expect, it } from 'vitest';
import {
  KNOWN_ADDRESS,
  addressFor,
  allChecksPass,
  base58Decode,
  base58Encode,
  checksumIndex,
  crc32,
  fromHex,
  keysFromSeed,
  mixEntropy,
  mnemonicFromSeed,
  parseAddress,
  publicFromSecret,
  reduceScalar,
  seedFromMnemonic,
  selfTest,
  toHex,
  walletFromMnemonic,
  walletFromSeed,
} from '../src/client/monero';
import { MONERO_WORDS, PREFIX_LENGTH } from '../src/client/monero-words';

const seedFrom = (text: string) => {
  // A deterministic 32 bytes, so every test here is reproducible.
  const out = new Uint8Array(32);
  for (let i = 0; i < 32; i++) out[i] = (text.charCodeAt(i % text.length) * (i + 7)) & 0xff;
  return reduceScalar(out);
};

describe('the word list', () => {
  it('is exactly 1626 words', () => {
    // Not a round number and not negotiable: the phrase encodes in base 1626.
    // A list one word short or long changes what every phrase decodes to.
    expect(MONERO_WORDS).toHaveLength(1626);
  });

  it('is unique in the first three characters', () => {
    // The checksum word is computed from three-character prefixes, so a
    // collision would make two different phrases indistinguishable to it.
    expect(new Set(MONERO_WORDS.map((w) => w.slice(0, PREFIX_LENGTH))).size).toBe(1626);
  });

  it('starts and ends where the Monero source does', () => {
    expect(MONERO_WORDS[0]).toBe('abbey');
    expect(MONERO_WORDS[1625]).toBe('zoom');
  });
});

describe('scalar reduction', () => {
  it('leaves a value already below the order alone', () => {
    const small = new Uint8Array(32);
    small[0] = 42;
    expect(toHex(reduceScalar(small))).toBe(toHex(small));
  });

  it('brings an out-of-range value into the field', () => {
    // All-ones is far above the group order; reducing must change it, and the
    // result must be below the order.
    const big = new Uint8Array(32).fill(0xff);
    const reduced = reduceScalar(big);
    expect(toHex(reduced)).not.toBe(toHex(big));
    // Top byte of the order is 0x10, so a reduced scalar cannot exceed it.
    expect(reduced[31]!).toBeLessThanOrEqual(0x10);
  });

  it('is idempotent, because a reduced scalar is already reduced', () => {
    const once = reduceScalar(new Uint8Array(32).fill(0xab));
    expect(toHex(reduceScalar(once))).toBe(toHex(once));
  });

  it('refuses anything that is not 32 bytes', () => {
    expect(() => reduceScalar(new Uint8Array(31))).toThrow();
  });
});

describe('public keys', () => {
  it('gives the published ed25519 base point for a scalar of one', () => {
    // The one external vector available for this step, and everybody agrees
    // on it.
    expect(toHex(publicFromSecret(fromHex('01' + '00'.repeat(31))))).toBe(
      '5866666666666666666666666666666666666666666666666666666666666666',
    );
  });

  it('refuses a zero scalar rather than returning the identity', () => {
    expect(() => publicFromSecret(new Uint8Array(32))).toThrow(/zero/i);
  });

  it('is deterministic', () => {
    const secret = seedFrom('determinism');
    expect(toHex(publicFromSecret(secret))).toBe(toHex(publicFromSecret(secret)));
  });

  it('gives different keys for different secrets', () => {
    expect(toHex(publicFromSecret(seedFrom('one')))).not.toBe(toHex(publicFromSecret(seedFrom('two'))));
  });
});

describe('key derivation', () => {
  it('derives the view key from the spend key, which is what one phrase restores', () => {
    const keys = keysFromSeed(seedFrom('derivation'));
    // Same seed, same view key, every time and in every implementation.
    expect(toHex(keysFromSeed(seedFrom('derivation')).viewSecret)).toBe(toHex(keys.viewSecret));
    expect(toHex(keys.viewSecret)).not.toBe(toHex(keys.spendSecret));
  });

  it('produces four distinct 32-byte values', () => {
    const keys = keysFromSeed(seedFrom('distinct'));
    const all = [keys.spendSecret, keys.viewSecret, keys.spendPublic, keys.viewPublic];
    for (const value of all) expect(value).toHaveLength(32);
    expect(new Set(all.map(toHex)).size).toBe(4);
  });

  it('gives a view secret that is a valid scalar', () => {
    const keys = keysFromSeed(seedFrom('reduced view'));
    expect(toHex(reduceScalar(keys.viewSecret))).toBe(toHex(keys.viewSecret));
  });
});

describe('base58, the Monero variant', () => {
  it('round-trips the real address to the character', () => {
    // The strongest check here: this address came out of the official Monero
    // wallet, not out of this code.
    expect(base58Encode(base58Decode(KNOWN_ADDRESS))).toBe(KNOWN_ADDRESS);
  });

  it('turns 69 bytes into 95 characters, which is what an address is', () => {
    expect(base58Decode(KNOWN_ADDRESS)).toHaveLength(69);
    expect(KNOWN_ADDRESS).toHaveLength(95);
  });

  it('round-trips arbitrary lengths, including the awkward partial block', () => {
    for (let length = 1; length <= 20; length++) {
      const bytes = new Uint8Array(length);
      for (let i = 0; i < length; i++) bytes[i] = (i * 37 + 11) & 0xff;
      expect(toHex(base58Decode(base58Encode(bytes))), `length ${length}`).toBe(toHex(bytes));
    }
  });

  it('keeps leading zero bytes, which a naive base58 loses', () => {
    const bytes = new Uint8Array([0, 0, 0, 1, 2, 3, 4, 5]);
    expect(toHex(base58Decode(base58Encode(bytes)))).toBe(toHex(bytes));
  });

  it('rejects a character outside the alphabet', () => {
    expect(() => base58Decode('0OIl' + 'a'.repeat(7))).toThrow(/base58/i);
  });
});

describe('parsing an address', () => {
  it('reads the site donation address correctly', () => {
    const parsed = parseAddress(KNOWN_ADDRESS);
    expect(parsed.valid).toBe(true);
    expect(parsed.network).toBe('mainnet');
    expect(parsed.kind).toBe('subaddress');
    expect(parsed.spendPublic).toHaveLength(64);
    expect(parsed.viewPublic).toHaveLength(64);
  });

  it('catches a single mistyped character', () => {
    // The entire point of a checksum, and the failure people actually hit.
    const broken = KNOWN_ADDRESS.slice(0, 40) + (KNOWN_ADDRESS[40] === 'a' ? 'b' : 'a') + KNOWN_ADDRESS.slice(41);
    const parsed = parseAddress(broken);
    expect(parsed.valid).toBe(false);
    expect(parsed.problem).toMatch(/checksum|mistyped|block/i);
  });

  it('catches truncation', () => {
    expect(parseAddress(KNOWN_ADDRESS.slice(0, 90)).valid).toBe(false);
  });

  it('says what is wrong rather than just failing', () => {
    expect(parseAddress('').problem).toBeTruthy();
    expect(parseAddress('not an address').problem).toBeTruthy();
    expect(parseAddress('4' + 'a'.repeat(94)).problem).toBeTruthy();
  });

  it('does not mistake a Bitcoin address for a Monero one', () => {
    expect(parseAddress('1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa').valid).toBe(false);
  });

  it('recognises an address this code built', () => {
    const wallet = walletFromSeed(seedFrom('built here'));
    const parsed = parseAddress(wallet.address);
    expect(parsed.valid).toBe(true);
    expect(parsed.kind).toBe('standard');
    expect(parsed.spendPublic).toBe(wallet.spendPublic);
    expect(parsed.viewPublic).toBe(wallet.viewPublic);
  });

  it('tells the networks apart', () => {
    const keys = keysFromSeed(seedFrom('networks'));
    for (const network of ['mainnet', 'stagenet', 'testnet'] as const) {
      const address = addressFor(keys.spendPublic, keys.viewPublic, network);
      expect(parseAddress(address).network, network).toBe(network);
    }
  });

  it('gives mainnet addresses the 4 they are known by', () => {
    const keys = keysFromSeed(seedFrom('prefix four'));
    expect(addressFor(keys.spendPublic, keys.viewPublic, 'mainnet').startsWith('4')).toBe(true);
  });
});

describe('the seed phrase', () => {
  it('is 25 words', () => {
    expect(mnemonicFromSeed(seedFrom('twenty five'))).toHaveLength(25);
  });

  it('round-trips to the same bytes', () => {
    for (const label of ['a', 'longer input here', 'another one entirely', 'x']) {
      const seed = seedFrom(label);
      const back = seedFromMnemonic(mnemonicFromSeed(seed));
      expect(back.problem, label).toBeNull();
      expect(toHex(back.seed!), label).toBe(toHex(seed));
    }
  });

  it('repeats one of its own words as the checksum', () => {
    const phrase = mnemonicFromSeed(seedFrom('checksum word'));
    expect(phrase.slice(0, 24)).toContain(phrase[24]);
    expect(phrase[24]).toBe(phrase[checksumIndex(phrase.slice(0, 24))]);
  });

  it('catches a single word swapped for another real word', () => {
    // The case the checksum exists for: a word that is in the list, in the
    // wrong place, which nothing else would notice.
    const phrase = mnemonicFromSeed(seedFrom('swap detection'));
    const broken = [...phrase];
    broken[5] = MONERO_WORDS[(MONERO_WORDS.indexOf(broken[5]!) + 1) % 1626]!;
    const result = seedFromMnemonic(broken);
    expect(result.seed).toBeNull();
    expect(result.problem).toMatch(/last word should be/i);
  });

  it('names a word that is not in the list', () => {
    const phrase = mnemonicFromSeed(seedFrom('unknown word'));
    const broken = [...phrase];
    broken[3] = 'zzzznotaword';
    expect(seedFromMnemonic(broken).problem).toMatch(/zzzznotaword/);
  });

  it('counts the words and says the number', () => {
    expect(seedFromMnemonic('one two three').problem).toMatch(/25 words and this is 3/);
  });

  it('accepts a phrase as a string with any spacing, and ignores case', () => {
    const phrase = mnemonicFromSeed(seedFrom('spacing'));
    const messy = '  ' + phrase.join('   ').toUpperCase() + '\n';
    expect(toHex(seedFromMnemonic(messy).seed!)).toBe(toHex(seedFromMnemonic(phrase).seed!));
  });

  it('restores to the same wallet it came from', () => {
    // The property that matters most to somebody holding a piece of paper.
    const wallet = walletFromSeed(seedFrom('restore me'));
    const restored = walletFromMnemonic(wallet.mnemonic);
    expect('problem' in restored).toBe(false);
    expect((restored as typeof wallet).address).toBe(wallet.address);
    expect((restored as typeof wallet).spendSecret).toBe(wallet.spendSecret);
  });
});

describe('crc32 and the checksum word', () => {
  it('matches the published value for a known string', () => {
    // The standard IEEE CRC-32 check value.
    expect(crc32('123456789') >>> 0).toBe(0xcbf43926);
  });

  it('picks the same checksum word Monero itself picks', () => {
    // The one place a step of this derivation can be checked against the
    // official implementation's own output rather than against a round trip.
    // This seed and its checksum word are lifted from Monero's unit tests
    // (tests/unit_tests/mnemonics.cpp, the bad-checksum language-detection
    // case). Portuguese, so four-character prefixes rather than three, which
    // is why checksumIndex takes the length as an argument.
    const portuguese = ('cinzento luxuriante leonardo gnostico digressao cupula fifa broxar iniquo ' +
      'louvor ovario dorsal ideologo besuntar decurso rosto susto lemure unheiro pagodeiro ' +
      'nitroglicerina eclusa mazurca bigorna').split(' ');
    expect(portuguese).toHaveLength(24);
    expect(portuguese[checksumIndex(portuguese, 4)]).toBe('gnostico');
  });

  it('would not match if the prefix length were wrong', () => {
    // Guards the test above from passing by luck: three characters must give
    // a different answer, or it is proving nothing about the prefix rule.
    const portuguese = ('cinzento luxuriante leonardo gnostico digressao cupula fifa broxar iniquo ' +
      'louvor ovario dorsal ideologo besuntar decurso rosto susto lemure unheiro pagodeiro ' +
      'nitroglicerina eclusa mazurca bigorna').split(' ');
    expect(checksumIndex(portuguese, 3)).not.toBe(checksumIndex(portuguese, 4));
  });
});

describe('a wallet', () => {
  it('writes its phrase from the reduced key, not the raw seed', () => {
    // The subtle, silent, expensive bug this whole file is careful about: if
    // the phrase encoded unreduced randomness, the words on the paper would
    // restore to a different wallet than the address printed beside them.
    const raw = new Uint8Array(32).fill(0xff);
    const wallet = walletFromSeed(raw);
    const restored = walletFromMnemonic(wallet.mnemonic) as typeof wallet;
    expect(restored.address).toBe(wallet.address);
    expect(restored.spendSecret).toBe(wallet.spendSecret);
    // And the seed really was out of range, so this test is testing something.
    expect(toHex(reduceScalar(raw))).not.toBe(toHex(raw));
  });

  it('is entirely determined by its seed', () => {
    const a = walletFromSeed(seedFrom('same'));
    const b = walletFromSeed(seedFrom('same'));
    expect(a).toEqual(b);
  });

  it('gives every field as hex of the right length', () => {
    const wallet = walletFromSeed(seedFrom('fields'));
    for (const key of ['spendSecret', 'viewSecret', 'spendPublic', 'viewPublic'] as const) {
      expect(wallet[key], key).toMatch(/^[0-9a-f]{64}$/);
    }
  });

  it('reports a bad phrase rather than throwing', () => {
    expect(walletFromMnemonic('not a real phrase')).toHaveProperty('problem');
  });
});

describe('the self test the page runs before it will generate anything', () => {
  it('passes, in full', () => {
    const checks = selfTest();
    const failed = checks.filter((c) => !c.ok);
    expect(failed.map((c) => `${c.name}: ${c.detail}`)).toEqual([]);
    expect(allChecksPass(checks)).toBe(true);
  });

  it('checks the things that would be silent failures', () => {
    const names = selfTest().map((c) => c.name.toLowerCase());
    expect(names.some((n) => n.includes('keccak'))).toBe(true);
    expect(names.some((n) => n.includes('base point'))).toBe(true);
    expect(names.some((n) => n.includes('real address'))).toBe(true);
    expect(names.some((n) => n.includes('phrase'))).toBe(true);
  });

  it('says what each check proves, not just whether it passed', () => {
    // A green tick nobody can interpret is decoration. The page prints these.
    for (const check of selfTest()) {
      expect(check.proves.length, check.name).toBeGreaterThan(30);
    }
  });

  it('reports failure rather than throwing when something is broken', () => {
    expect(allChecksPass([{ name: 'x', proves: 'y', ok: false, detail: '' }])).toBe(false);
    expect(allChecksPass([])).toBe(false);
  });
});

describe('the donation address', () => {
  it('is the same string the site prints in its footer', async () => {
    const { DONATION_ADDRESS } = await import('../src/worker/html');
    expect(KNOWN_ADDRESS).toBe(DONATION_ADDRESS);
  });

  it('is a valid mainnet address', () => {
    // If this ever fails, the site is asking people to send money into a hole.
    const parsed = parseAddress(KNOWN_ADDRESS);
    expect(parsed.valid).toBe(true);
    expect(parsed.network).toBe('mainnet');
  });
});

describe('mixing in your own entropy', () => {
  const browser = () => {
    const b = new Uint8Array(32);
    for (let i = 0; i < 32; i++) b[i] = (i * 91 + 5) & 0xff;
    return b;
  };

  it('hashes, rather than returning the input', () => {
    // The bug this replaced: a version that folded bytes together without
    // hashing, while the page said it hashed. Same length, plausible output,
    // completely different property.
    expect(toHex(mixEntropy(browser()))).not.toBe(toHex(browser()));
  });

  it('changes completely when one character of the extra changes', () => {
    const a = mixEntropy(browser(), new TextEncoder().encode('6 4 2 1 5 3'));
    const b = mixEntropy(browser(), new TextEncoder().encode('6 4 2 1 5 4'));
    expect(toHex(a)).not.toBe(toHex(b));
    // And not merely in the last byte: a hash, not a checksum.
    const differing = [...a].filter((byte, i) => byte !== b[i]).length;
    expect(differing).toBeGreaterThan(20);
  });

  it('is deterministic for the same inputs', () => {
    const extra = new TextEncoder().encode('dice');
    expect(toHex(mixEntropy(browser(), extra))).toBe(toHex(mixEntropy(browser(), extra)));
  });

  it('works with no extra at all', () => {
    expect(mixEntropy(browser())).toHaveLength(32);
    expect(mixEntropy(browser(), new Uint8Array(0))).toHaveLength(32);
  });

  it('insists the browser actually supplied 32 bytes', () => {
    expect(() => mixEntropy(new Uint8Array(16))).toThrow(/32 bytes/);
  });

  it('produces a usable wallet', () => {
    const wallet = walletFromSeed(mixEntropy(browser(), new TextEncoder().encode('4 4 6 1')));
    expect(parseAddress(wallet.address).valid).toBe(true);
  });
});
